version: '3'
services:
  master:
    image: base/key-generation-service
    container_name: key-generation-service-master
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 10000:8080
  backup:
    image: base/key-generation-service
    container_name: key-generation-service-backup
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 10001:8080